name: Reusable workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the user'
        required: true
        type: string
     run-tests:
        description: 'Wether to run tests'
        required: false
        default: 'false'
        type: boolean
    branches:
       - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Greet the user
        uses: echo "Hello, ${{ inputs.name }}

  test-job:
    if: ${{ inputs.run-tests }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..."
